### ISSUE TITLE
puush-area not working with tiling window manager?

### ISSUE THREAD

**Issue by patoupatou** [sgoo/puush-linux#5]
I'm using arch-linux with i3 as my window manager (no DE) and I've setupped everything and puushing to clipboard works perfectly except the capture area one.

When I try to capture an area it just opens a new window where I can only select from this window, and it seems to randomly puush an area. Well, not perfectly random, as when I try to select the uppper corner of that window, it will select the upper corner of my whole screen, but I can only select inside that window...

Any input on this?

Thanks

**Comment by patoupatou** [comment]
http://puu.sh/gyzkn/f06008fa17.png
Here's a full desktop puu.sh of the problem in question. When I run puush-area.py this weird box opens on the side and I can only select from it, thus puushing random stuff.

**Comment by sgoo** [comment]
Its very hack in the way this works, it starts a new window over the top of everything and uses that window to capture the area. I'm not surprised it doesn't work with a window manager like yours.
Making it do area select in your window manager will probably require significant changes to the way it currently works and I don't have the time to do that work sorry.

**Comment by patoupatou** [comment]
Yea I figured that was the problem, the puu.sh area will be correct if I put this new window fullscreen. The problem is that when fullscreen this window is not transparent so I cannot see behind it :(

But thanks for answering.
